use blackswan_event_tracker;
SELECT * FROM user;
SELECT * FROM event;
SELECT * FROM post;
SELECT * FROM tag;
SELECT * FROM url;
SELECT * FROM media;
SELECT * FROM location;
SELECT * FROM postevent;
SELECT * FROM tagevent;
SELECT * FROM url_post;
SELECT * FROM media_post;
